### ISSUE TITLE
mbed does not compile with --std=c++11 since 5.4.0

### ISSUE THREAD

**Issue by akiroz** [platformio/platform-ststm32#244]
mbed compile error with `--std=c++11` since release `5.4.0`, tested on macOS and Arch Linux.

Error message:
```
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp: In function 'int settimeofday(const timeval*, const timezone*)':
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:89:22: error: invalid use of incomplete type 'const struct timeval'
_rtc_write(tv->tv_sec);
^~
In file included from /.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:20:0:
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.h:111:25: note: forward declaration of 'struct timeval'
int gettimeofday(struct timeval *tv, void *tz);
^~~~~~~
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:89:24: error: invalid use of incomplete type 'const struct timeval'
_rtc_write(tv->tv_sec);
^~~~~~
In file included from /.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:20:0:
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.h:111:25: note: forward declaration of 'struct timeval'
int gettimeofday(struct timeval *tv, void *tz);
^~~~~~~
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp: In function 'int gettimeofday(timeval*, void*)':
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:110:7: error: invalid use of incomplete type 'struct timeval'
tv->tv_sec  = t;
^~
In file included from /.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:20:0:
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.h:111:25: note: forward declaration of 'struct timeval'
int gettimeofday(struct timeval *tv, void *tz);
^~~~~~~
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:110:9: error: invalid use of incomplete type 'struct timeval'
tv->tv_sec  = t;
^~~~~~
In file included from /.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:20:0:
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.h:111:25: note: forward declaration of 'struct timeval'
int gettimeofday(struct timeval *tv, void *tz);
^~~~~~~
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:111:7: error: invalid use of incomplete type 'struct timeval'
tv->tv_usec = 0;
^~
In file included from /.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:20:0:
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.h:111:25: note: forward declaration of 'struct timeval'
int gettimeofday(struct timeval *tv, void *tz);
^~~~~~~
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:111:9: error: invalid use of incomplete type 'struct timeval'
tv->tv_usec = 0;
^~~~~~~
In file included from /.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:20:0:
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.h:111:25: note: forward declaration of 'struct timeval'
int gettimeofday(struct timeval *tv, void *tz);
^~~~~~~
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp: In function 'time_t time(time_t*)':
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:124:20: error: aggregate 'timeval tv' has incomplete type and cannot be defined
struct timeval tv;
^~
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp: In function 'void set_time(time_t)':
/.platformio/packages/framework-mbed/platform/mbed_rtc_time.cpp:137:26: error: variable 'const timeval tv' has initializer but incomplete type
const struct timeval tv = { t, 0 };
^~
*** [.pioenvs/default/FrameworkMbed/platform/mbed_rtc_time.o] Error 1
```

platformio.ini:
```
[env:default]
platform = ststm32@5.4.0
framework = mbed
board = bluepill_f103c8
upload_protocol = jlink

build_flags = -std=c++11
build_unflags = -std=gnu++98
```

**Comment by valeros** [comment]
Please use C++11 with GNU extensions:
```
build_flags = -std=gnu++11
build_unflags = -std=gnu++98
```
