### ISSUE TITLE
example mbed-rtos-ethernet-tls compile errors

### ISSUE THREAD

**Issue by monowii** [platformio/platform-ststm32#701]
Hello,
I'm trying to use Ethernet on NUCLEO_H743ZI2 but is not working on latest platformio core 6.1.7, ST STM32 15.6.0

As a starting point I tried to compile the example mbed-rtos-ethernet-tls without any modifications:
```
error: 'nsapi_size_or_error_t' was not declared in this scope
error: 'nsapi_size_t' was not declared in this scope
error: 'NetworkInterface' was not declared in this scope
[...]
```
MBED_CONF_NSAPI_PRESENT is not defined, and mbed.h cannot include "netsocket/nsapi.h" nor "netsocket/nsapi_ppp.h"

On latest Mbed Studio this same example is working correctly (using Mbed OS 6.17)

Thanks for you help
